version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fast-food
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - fastfood_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fast-food
    ports:
      - "5443:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastfood_network

volumes:
  postgres_data:

networks:
  fastfood_network:
    driver: bridge