version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fast-food
    ports:
      - "5443:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: