server:
  port: ${PORT:8080}

spring:
  application:
    name: fast-food
  datasource:
    url: jdbc:postgresql://localhost:5443/fast-food
    username: postgres
    password: postgres
    #initialization-mode: always  # Garante que o Spring execute o script
    #initialization-sql: classpath:script.sql  # Localiza o arquivo init.sql
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5443/fast-food
    user: postgres
    password: postgres
    locations: classpath:db/migration

